theme: jekyll-theme-minimal
title: Nathaniel Trief's Data Portfolio
description: Professional data science portfolio showcasing projects in Python, SQL, JavaScript, Machine Learning, and Business Intelligence
